// API Route: Analyze data using Google Gemini AI
// Extracts insights, patterns, and generates presentation structure

import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

// Initialize Gemini AI
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export async function POST(request: NextRequest) {
    try {
        const { data, customInstructions, fileType } = await request.json();

        if (!process.env.GEMINI_API_KEY) {
            return NextResponse.json(
                { error: 'Gemini API key not configured' },
                { status: 500 }
            );
        }

        if (!data) {
            return NextResponse.json(
                { error: 'No data provided' },
                { status: 400 }
            );
        }

        // Get Gemini model
        const model = genAI.getGenerativeModel({
            model: process.env.GEMINI_MODEL || 'gemini-pro'
        });

        // Construct analysis prompt
        const prompt = constructAnalysisPrompt(data, customInstructions, fileType);

        // Generate analysis
        const result = await model.generateContent(prompt);
        const response = await result.response;
        const analysisText = response.text();

        // Parse AI response into structured data
        const analyzedData = parseAIResponse(analysisText);

        return NextResponse.json({
            success: true,
            analysis: analyzedData,
            rawResponse: analysisText,
        });

    } catch (error: any) {
        console.error('Analysis error:', error);
        return NextResponse.json(
            {
                error: 'Failed to analyze data',
                details: error.message
            },
            { status: 500 }
        );
    }
}

// Construct analysis prompt for Gemini
function constructAnalysisPrompt(
    data: any,
    customInstructions: string,
    fileType: string
): string {
    const dataStr = JSON.stringify(data, null, 2).substring(0, 10000); // Limit size

    return `You are a data analysis expert. Analyze the following ${fileType} data and provide comprehensive insights.

DATA:
${dataStr}

CUSTOM INSTRUCTIONS:
${customInstructions || 'No specific instructions provided.'}

Please provide your analysis in the following JSON format:
{
  "title": "Suggested presentation title",
  "subtitle": "Suggested subtitle",
  "summary": "Executive summary (2-3 sentences)",
  "keyMetrics": [
    { "label": "Metric name", "value": "Value", "trend": "up/down/neutral" }
  ],
  "insights": [
    "Key insight 1",
    "Key insight 2",
    "Key insight 3"
  ],
  "categories": [
    "Category 1",
    "Category 2"
  ],
  "recommendations": [
    {
      "priority": "HIGH/MEDIUM/LOW",
      "title": "Recommendation title",
      "description": "Detailed description"
    }
  ],
  "visualizations": [
    {
      "type": "metric-cards/bar-chart/pie-chart/timeline/swot",
      "title": "Visualization title",
      "data": {}
    }
  ]
}

Analyze the data thoroughly and identify:
1. Key metrics and KPIs (3-5 primary indicators)
2. Notable patterns, trends, and anomalies
3. Categories and groupings
4. Time-based data for timelines
5. Problems, opportunities, strengths, weaknesses
6. Actionable recommendations

Provide ONLY the JSON response, no additional text.`;
}

// Parse AI response into structured format
function parseAIResponse(responseText: string): any {
    try {
        // Remove markdown code blocks if present
        let cleaned = responseText.trim();
        if (cleaned.startsWith('```json')) {
            cleaned = cleaned.replace(/```json\n?/g, '').replace(/```\n?/g, '');
        } else if (cleaned.startsWith('```')) {
            cleaned = cleaned.replace(/```\n?/g, '');
        }

        // Parse JSON
        const parsed = JSON.parse(cleaned);

        // Ensure required fields exist
        return {
            title: parsed.title || 'Data Analysis Report',
            subtitle: parsed.subtitle || 'Generated by DataViz Studio',
            summary: parsed.summary || 'Comprehensive analysis of your data.',
            keyMetrics: parsed.keyMetrics || [],
            insights: parsed.insights || [],
            categories: parsed.categories || [],
            recommendations: parsed.recommendations || [],
            visualizations: parsed.visualizations || [],
        };

    } catch (error) {
        console.error('Failed to parse AI response:', error);

        // Return default structure if parsing fails
        return {
            title: 'Data Analysis Report',
            subtitle: 'Generated by DataViz Studio',
            summary: 'Analysis of your uploaded data.',
            keyMetrics: [
                { label: 'Total Items', value: 'N/A', trend: 'neutral' },
            ],
            insights: [
                'Data has been processed successfully.',
                'Review the detailed sections for more information.',
            ],
            categories: ['General'],
            recommendations: [],
            visualizations: [],
        };
    }
}
